<?php
declare(strict_types=1);
$sources=require __DIR__.'/sources.php';
$phase2=[];
// Cross-jurisdiction guides are not tied to one authority; the page links to every jurisdiction's official source instead.
$global=['label'=>'Global','authority'=>'The competent registry or government authority in your chosen jurisdiction','note'=>'Each jurisdiction has its own registry, licensing and tax authorities. Identify the authority that controls your exact entity, activity and location, and use its current guidance as the controlling source.','verified'=>'2026-09-25','global'=>true];

function p2_make(array $src, string $slug, string $title, string $h1, string $description, string $answer, array $focus, array $extraFaqs=[], array $extraSections=[]): array {
  $global=!empty($src['global']);
  $sections=[
    ['title'=>$global?'Which authority applies':'Official-source position','body'=>$src['note']],
    ['title'=>'Practical checklist','bullets'=>$focus],
  ];
  foreach($extraSections as $s){ $sections[]=$s; }
  $faqs=[
    ['q'=>'Which authority controls this topic?','a'=>$global?'It depends on the jurisdiction. Use the official source directory on this page to find the registry or government authority for your jurisdiction, and use its current guidance before acting.':$src['authority'].' is the primary authority linked on this page; use its current service or guidance page before acting.'],

  ];
  foreach($extraFaqs as $f){ $faqs[]=$f; }
  return [
    'slug'=>$slug,'jurisdiction'=>$global?null:strtok($slug,'/'),'kind'=>$global?'resource':'guide','name'=>$title,'title'=>$title.' | INCORPSYS','h1'=>$h1,'eyebrow'=>$global?'RESOURCE GUIDE':'IN-DEPTH JURISDICTION GUIDE',
    'description'=>$description,'answer'=>$answer,'sections'=>$sections,'source'=>$global?null:$src,'faqs'=>$faqs,'verified'=>$src['verified']
  ];
}


$phase2['uae/business-activity-selection']=p2_make($sources['uae'], 'uae/business-activity-selection', 'Business Activity Selection in UAE', 'Business Activity Selection in UAE', 'Source-backed INCORPSYS guide to business activity selection in UAE, with official verification, practical checklists and clear next steps.', 'Start with the activity because the official UAE Government says it is the basis for selecting the legal form and licence type.', ['Identify the intended activity in the official classification.','Check whether the activity is commercial, industrial, professional or another category.','Confirm if the activity needs an external approval before filing.','Keep the authority page used for the activity decision in the case file.']);
$phase2['uae/legal-form-selection']=p2_make($sources['uae'], 'uae/legal-form-selection', 'Legal Form Selection in UAE', 'Legal Form Selection in UAE', 'Source-backed INCORPSYS guide to legal form selection in UAE, with official verification, practical checklists and clear next steps.', 'Select the legal form only after the activity and ownership model are clear; the official guidance links legal form to the applicable laws and licensing route.', ['Compare the legal forms listed by the UAE Government.','Match the proposed form to the actual business activity.','Check ownership-specific conditions that may apply.','Confirm the selected form with the relevant emirate authority.']);
$phase2['uae/trade-licence-categories']=p2_make($sources['uae'], 'uae/trade-licence-categories', 'Trade Licence Categories in UAE', 'Trade Licence Categories in UAE', 'Source-backed INCORPSYS guide to trade licence categories in UAE, with official verification, practical checklists and clear next steps.', 'Use the official licensing categories as the starting point, then verify emirate-specific licence pathways and activity requirements.', ['Review the relevant licence category.','Check whether the chosen emirate has additional licence types.','Confirm activity-specific approvals.','Use the current authority fee and service page before payment.']);
$phase2['uae/trade-name-registration']=p2_make($sources['uae'], 'uae/trade-name-registration', 'Trade Name Registration in UAE', 'Trade Name Registration in UAE', 'Source-backed INCORPSYS guide to trade name registration in UAE, with official verification, practical checklists and clear next steps.', 'A trade name is a formal registration step in the UAE mainland process; the official guidance publishes naming conditions and the local economic authority route.', ['Check whether the proposed name is already registered.','Review the legal-form suffix requirement.','Check restricted or inappropriate naming conditions.','Retain the official trade-name application evidence.']);
$phase2['uae/initial-approval']=p2_make($sources['uae'], 'uae/initial-approval', 'Initial Approval in UAE', 'Initial Approval in UAE', 'Source-backed INCORPSYS guide to initial approval in UAE, with official verification, practical checklists and clear next steps.', 'The UAE Government describes initial approval as a no-objection step that allows progress to subsequent setup steps; it is not itself authority to conduct the business activity.', ['Confirm whether initial approval is required.','Check if the activity needs a prior sector approval.','Do not treat initial approval as a licence to operate.','Keep the approval evidence with the incorporation file.']);
$phase2['uae/memorandum-and-service-agent']=p2_make($sources['uae'], 'uae/memorandum-and-service-agent', 'MOA and Service-Agent Documentation in UAE', 'MOA and Service-Agent Documentation in UAE', 'Source-backed INCORPSYS guide to MOA and service-agent documentation in UAE, with official verification, practical checklists and clear next steps.', 'Depending on the legal form, the official process may require a Memorandum of Association or a local service-agent agreement; the exact document route should be verified before execution.', ['Confirm the legal form first.','Check whether an MOA or other agreement applies.','Verify attestation or notarisation steps with the relevant authority.','Store signed and final documents with filing evidence.']);
$phase2['uae/business-location']=p2_make($sources['uae'], 'uae/business-location', 'Business Location Requirements in UAE', 'Business Location Requirements in UAE', 'Source-backed INCORPSYS guide to business location requirements in UAE, with official verification, practical checklists and clear next steps.', 'The official mainland guidance states that businesses need a physical operating address and that premises requirements are governed locally.', ['Check the applicable emirate premises rules.','Verify lease and attestation requirements.','For Dubai, check the official Ejari route where applicable.','Confirm that the location supports the licensed activity.']);
$phase2['uae/additional-government-approvals']=p2_make($sources['uae'], 'uae/additional-government-approvals', 'Additional Government Approvals in UAE', 'Additional Government Approvals in UAE', 'Source-backed INCORPSYS guide to additional government approvals in UAE, with official verification, practical checklists and clear next steps.', 'Certain activities can require approvals from specialised government entities in addition to the main incorporation and licensing steps.', ['Identify whether the activity is regulated.','Map the relevant sector authority.','Secure any required approval before completing the final licence route.','Keep approval letters and references in the corporate file.']);
$phase2['uae/licence-document-collection']=p2_make($sources['uae'], 'uae/licence-document-collection', 'Licence Issuance and Document Collection in UAE', 'Licence Issuance and Document Collection in UAE', 'Source-backed INCORPSYS guide to licence issuance and document collection in UAE, with official verification, practical checklists and clear next steps.', 'After the required steps are completed, the official guidance explains that the business licence can be collected through the relevant economic department or digital channel.', ['Confirm all prior approvals are complete.','Keep the initial-approval and supporting documents together.','Verify lease and MOA evidence as applicable.','Check the authority payment and collection instructions.']);
$phase2['uae/online-startup-route']=p2_make($sources['uae'], 'uae/online-startup-route', 'Online Business Setup Route in UAE', 'Online Business Setup Route in UAE', 'Source-backed INCORPSYS guide to online business setup route in UAE, with official verification, practical checklists and clear next steps.', 'The UAE Government also describes online routes such as Basher for establishing businesses; the exact workflow and eligibility should be checked directly on the live government portal.', ['Confirm the online route is suitable for the business.','Use the official portal rather than third-party links.','Check the documents and approvals required by the current workflow.','Retain the official transaction reference.']);

$phase2['singapore/eligibility-and-foreigners']=p2_make($sources['singapore'], 'singapore/eligibility-and-foreigners', 'Eligibility and Foreign-Founder Rules in Singapore', 'Eligibility and Foreign-Founder Rules in Singapore', 'Source-backed INCORPSYS guide to eligibility and foreign-founder rules in Singapore, with official verification, practical checklists and clear next steps.', 'ACRA explains who needs to register a business and sets out additional rules for foreigners, including local-residency requirements and the use of a corporate service provider in certain cases.', ['Check whether the activity requires registration.','Identify the applicant role and Singpass status.','For foreign founders, verify the CSP and local-resident requirements.','Check current work-pass guidance separately if relocation is involved.']);
$phase2['singapore/business-structure']=p2_make($sources['singapore'], 'singapore/business-structure', 'Choosing a Business Structure in Singapore', 'Choosing a Business Structure in Singapore', 'Source-backed INCORPSYS guide to choosing a business structure in Singapore, with official verification, practical checklists and clear next steps.', 'ACRA places business structure before name selection and registration, and notes that the structure affects liability, cost and potential growth.', ['Choose the entity type that matches the intended activity.','Review the current structure-specific registration route.','Verify local-residency and officer requirements.','Keep the structure decision documented.']);
$phase2['singapore/business-name-choice']=p2_make($sources['singapore'], 'singapore/business-name-choice', 'Choosing a Business Name in Singapore', 'Choosing a Business Name in Singapore', 'Source-backed INCORPSYS guide to choosing a business name in Singapore, with official verification, practical checklists and clear next steps.', 'ACRA says a proposed name must be checked against existing and reserved names and may require referral approval depending on the name.', ['Search for identical or reserved names.','Review restrictions on protected or undesirable names.','Check whether referral approval may apply.','Confirm the selected name before preparing registration data.']);
$phase2['singapore/name-reservation-120-days']=p2_make($sources['singapore'], 'singapore/name-reservation-120-days', 'Name Reservation Period in Singapore', 'Name Reservation Period in Singapore', 'Source-backed INCORPSYS guide to name reservation period in Singapore, with official verification, practical checklists and clear next steps.', 'ACRA states that an approved business name can be reserved for up to 120 days and that the registration must be aligned with the reserved entity type.', ['Record the name-application transaction number.','Note the reservation expiry date.','Register the same entity type selected during reservation.','Do not rely on an expired reservation.']);
$phase2['singapore/ssic-business-activity-code']=p2_make($sources['singapore'], 'singapore/ssic-business-activity-code', 'SSIC and Business Activity Selection in Singapore', 'SSIC and Business Activity Selection in Singapore', 'Source-backed INCORPSYS guide to SSIC and business activity selection in Singapore, with official verification, practical checklists and clear next steps.', 'ACRA requires the applicant to select the most relevant Singapore Standard Industrial Classification (SSIC) code when applying for a business name.', ['Describe the intended activity clearly.','Select the most relevant SSIC code.','Check if the name triggers referral to another authority.','Retain the selected activity code in the filing checklist.']);
$phase2['singapore/local-company-bizfile']=p2_make($sources['singapore'], 'singapore/local-company-bizfile', 'Local Company Registration via Bizfile in Singapore', 'Local Company Registration via Bizfile in Singapore', 'Source-backed INCORPSYS guide to local company registration via Bizfile in Singapore, with official verification, practical checklists and clear next steps.', 'ACRA’s current Bizfile guide says a business name must be reserved before registering a local company, and the person who reserved the name can register it subject to the published rules.', ['Reserve the proposed company name first.','Prepare the registration information requested by Bizfile.','Confirm the filer is eligible to complete the registration.','Save the registration transaction records.']);
$phase2['singapore/business-address']=p2_make($sources['singapore'], 'singapore/business-address', 'Business Address Requirements in Singapore', 'Business Address Requirements in Singapore', 'Source-backed INCORPSYS guide to business address requirements in Singapore, with official verification, practical checklists and clear next steps.', 'ACRA’s guidance requires a business address and distinguishes the rules that can apply to home-based activities; a P.O. Box cannot be used as the main business address.', ['Prepare the business address before filing.','Check the home-office rules if relevant.','Do not use a P.O. Box as the business address.','Retain evidence of any address approvals required.']);
$phase2['singapore/registration-readiness']=p2_make($sources['singapore'], 'singapore/registration-readiness', 'Registration Readiness Checklist in Singapore', 'Registration Readiness Checklist in Singapore', 'Source-backed INCORPSYS guide to registration readiness checklist in Singapore, with official verification, practical checklists and clear next steps.', 'A source-first registration file should align identity, name, structure, activity, address and the applicant’s filing authority before the Bizfile submission.', ['Identity and filing authority checked.','Name reserved and transaction number recorded.','Business activity and SSIC code confirmed.','Address information ready.']);
$phase2['singapore/post-registration']=p2_make($sources['singapore'], 'singapore/post-registration', 'Post-Registration Requirements in Singapore', 'Post-Registration Requirements in Singapore', 'Source-backed INCORPSYS guide to post-registration requirements in Singapore, with official verification, practical checklists and clear next steps.', 'ACRA maintains a dedicated post-registration guide because incorporation or registration is followed by additional statutory and administrative requirements.', ['Open the current ACRA post-registration guidance.','Identify entity-specific follow-up obligations.','Calendar filings and changes that apply to the entity.','Keep the corporate profile and authority correspondence updated.']);
$phase2['singapore/foreign-founder-workflow']=p2_make($sources['singapore'], 'singapore/foreign-founder-workflow', 'Foreign Founder Setup Workflow in Singapore', 'Foreign Founder Setup Workflow in Singapore', 'Source-backed INCORPSYS guide to foreign founder setup workflow in Singapore, with official verification, practical checklists and clear next steps.', 'For overseas founders, start with ACRA’s eligibility and foreigner rules, then separate business-registration requirements from immigration or work-pass requirements.', ['Confirm whether a CSP is mandatory.','Check the local-resident requirement.','Complete the company-registration steps through the permitted channel.','Verify any immigration route separately with the relevant authority.']);

$phase2['hong-kong/company-types-and-name']=p2_make($sources['hong-kong'], 'hong-kong/company-types-and-name', 'Company Types and Name Selection in Hong Kong', 'Company Types and Name Selection in Hong Kong', 'Source-backed INCORPSYS guide to company types and name selection in Hong Kong, with official verification, practical checklists and clear next steps.', 'The Companies Registry describes company types and requires the proposed name to be checked against the public company-name index and applicable naming rules.', ['Choose the appropriate company type.','Search the proposed name using the official service.','Check for third-party intellectual-property conflicts.','Keep evidence of the name search.']);
$phase2['hong-kong/company-name-search']=p2_make($sources['hong-kong'], 'hong-kong/company-name-search', 'Official Company Name Search in Hong Kong', 'Official Company Name Search in Hong Kong', 'Source-backed INCORPSYS guide to official company name search in Hong Kong, with official verification, practical checklists and clear next steps.', 'The Hong Kong Companies Registry provides an e-Search route for checking whether a proposed name is identical to an existing or reserved name.', ['Use the exact proposed company name.','Check identical or reserved names.','Consider a separate trademark search.','Remember that final registrability is determined when the incorporation application is processed.']);
$phase2['hong-kong/incorporation-documents']=p2_make($sources['hong-kong'], 'hong-kong/incorporation-documents', 'Incorporation Documents in Hong Kong', 'Incorporation Documents in Hong Kong', 'Source-backed INCORPSYS guide to incorporation documents in Hong Kong, with official verification, practical checklists and clear next steps.', 'The Registry identifies core incorporation documents such as the applicable incorporation form, articles of association and notice to the Business Registration Office.', ['Confirm whether NNC1 or NNC1G applies.','Prepare the company articles.','Prepare the Business Registration Office notice.','Check for any additional information requested by the Registry.']);
$phase2['hong-kong/certificates']=p2_make($sources['hong-kong'], 'hong-kong/certificates', 'Incorporation Certificates in Hong Kong', 'Certificate of Incorporation and Business Registration in Hong Kong', 'Source-backed INCORPSYS guide to certificates of incorporation and business registration in Hong Kong, with official verification and next steps.', 'When an application is approved, the Registry issues the relevant certificates through electronic or hard-copy channels according to the filing route.', ['Use the official filing channel.','Monitor the registered user message box or collection notice.','Store both certificates with the incorporation record.','Confirm any separate permit needs for the planned activity.']);
$phase2['hong-kong/registered-office-rules']=p2_make($sources['hong-kong'], 'hong-kong/registered-office-rules', 'Registered Office Requirements in Hong Kong', 'Registered Office Requirements in Hong Kong', 'Source-backed INCORPSYS guide to registered office requirements in Hong Kong, with official verification, practical checklists and clear next steps.', 'The Companies Registry states that the registered office of a local limited company must be situated in Hong Kong.', ['Provide a Hong Kong registered office address.','Make sure the address is complete and usable for official notices.','Keep address-change evidence with corporate records.','Verify any service arrangement against the current law and authority guidance.']);
$phase2['hong-kong/directors-and-secretary']=p2_make($sources['hong-kong'], 'hong-kong/directors-and-secretary', 'Directors and Company Secretary in Hong Kong', 'Directors and Company Secretary in Hong Kong', 'Source-backed INCORPSYS guide to directors and company secretary in Hong Kong, with official verification, practical checklists and clear next steps.', 'The Registry’s incorporation FAQ describes director and company-secretary requirements for private companies and certain other company types.', ['Identify the first director(s).','Appoint a company secretary in accordance with the applicable rules.','Check residence and corporate-secretary conditions.','Avoid treating a service-provider assumption as a statutory rule.']);
$phase2['hong-kong/electronic-incorporation']=p2_make($sources['hong-kong'], 'hong-kong/electronic-incorporation', 'Electronic Incorporation in Hong Kong', 'Electronic Incorporation in Hong Kong', 'Source-backed INCORPSYS guide to electronic incorporation in Hong Kong, with official verification, practical checklists and clear next steps.', 'Hong Kong Companies Registry supports electronic filing through its e-Services infrastructure as well as hard-copy filing routes.', ['Create or use the appropriate e-Services account.','Prepare the forms in the required format.','Pay the current official fee through the stated channel.','Retain electronic submission evidence.']);
$phase2['hong-kong/business-licences']=p2_make($sources['hong-kong'], 'hong-kong/business-licences', 'Business Licences and Permits in Hong Kong', 'Business Licences and Permits in Hong Kong', 'Source-backed INCORPSYS guide to business licences and permits in Hong Kong, with official verification, practical checklists and clear next steps.', 'Incorporation does not automatically replace sector-specific permits; the Registry directs applicants to the relevant government information for additional licences and approvals.', ['Identify the planned business activities.','Check the Trade and Industry Department and other relevant authorities.','Obtain any required permit before operating a regulated activity.','Record the approval authority and validity information.']);
$phase2['hong-kong/non-hong-kong-company']=p2_make($sources['hong-kong'], 'hong-kong/non-hong-kong-company', 'Registering a Non-Hong Kong Company', 'Registering a Non-Hong Kong Company', 'Source-backed INCORPSYS guide to registration of a non-Hong Kong company, with official verification, practical checklists and clear next steps.', 'A company incorporated outside Hong Kong that establishes a place of business in Hong Kong may have a separate registration route with the Companies Registry.', ['Confirm whether the business has established a Hong Kong place of business.','Review the required registration form and certified documents.','Check the applicable timing rule.','Keep the overseas constitutional documents and accounts ready where required.']);
$phase2['hong-kong/e-services-and-protected-information']=p2_make($sources['hong-kong'], 'hong-kong/e-services-and-protected-information', 'E-Services and Protected Information in Hong Kong', 'E-Services and Protected Information in Hong Kong', 'Source-backed INCORPSYS guide to e-services and protected information in Hong Kong, with official verification, practical checklists and clear next steps.', 'The Companies Registry provides e-services for filings and separate rules for public inspection and protected information under the inspection regime.', ['Use the correct e-Services account type.','Understand which information is public and which is protected.','Keep director and company records consistent with filings.','Check the current Registry instructions before submitting sensitive information.']);

$phase2['uk/private-limited-company-type']=p2_make($sources['uk'], 'uk/private-limited-company-type', 'Choosing a Private Limited Company Type in UK', 'Choosing a Private Limited Company Type in UK', 'Source-backed INCORPSYS guide to choosing a private limited company type in UK, with official verification, practical checklists and clear next steps.', 'GOV.UK explains that the company setup route depends on the chosen company type and whether the company is limited by shares or guarantee.', ['Choose shares or guarantee based on the proposed structure.','Confirm the appropriate incorporation route.','Review the statutory records that will follow incorporation.','Keep the decision aligned with the business model.']);
$phase2['uk/directors-and-secretary']=p2_make($sources['uk'], 'uk/directors-and-secretary', 'Directors and Company Secretary in UK', 'Directors and Company Secretary in UK', 'Source-backed INCORPSYS guide to directors and company secretary in UK, with official verification, practical checklists and clear next steps.', 'A UK private company must appoint at least one director; a company secretary is optional for a private company under the GOV.UK formation guidance.', ['Identify at least one eligible director.','Decide whether a company secretary will be appointed.','Complete identity verification requirements if prompted.','Keep officer details current after incorporation.']);
$phase2['uk/shareholders']=p2_make($sources['uk'], 'uk/shareholders', 'Shareholders and Ownership in UK', 'Shareholders and Ownership in UK', 'Source-backed INCORPSYS guide to shareholders and ownership in UK, with official verification, practical checklists and clear next steps.', 'GOV.UK explains that a company limited by shares needs at least one shareholder and that a director can also be a shareholder.', ['Identify the initial shareholder(s).','Confirm share ownership information.','Prepare the statement of capital where required.','Keep ownership records consistent with the filed information.']);
$phase2['uk/people-with-significant-control']=p2_make($sources['uk'], 'uk/people-with-significant-control', 'People With Significant Control (PSC) in UK', 'People With Significant Control (PSC) in UK', 'Source-backed INCORPSYS guide to people with significant control (PSC) in UK, with official verification, practical checklists and clear next steps.', 'UK incorporation requires companies to identify people with significant control, including relevant ownership or voting control information.', ['Identify individuals or entities that meet the PSC test.','Gather the required PSC information.','Confirm PSC information during registration.','Keep the PSC register and filed details aligned.']);
$phase2['uk/constitutional-documents']=p2_make($sources['uk'], 'uk/constitutional-documents', 'Memorandum and Articles in UK', 'Memorandum and Articles in UK', 'Source-backed INCORPSYS guide to memorandum and articles in UK, with official verification, practical checklists and clear next steps.', 'GOV.UK lists constitutional and capital/guarantee documents as part of the formation process, depending on company type.', ['Prepare the required memorandum and articles.','Prepare the statement of capital or guarantee as applicable.','Review the company records that must be retained.','Ensure the filed documents match the chosen structure.']);
$phase2['uk/company-name-and-trademark']=p2_make($sources['uk'], 'uk/company-name-and-trademark', 'Company Name and Trademark Checks in UK', 'Company Name and Trademark Checks in UK', 'Source-backed INCORPSYS guide to company name and trademark checks in UK, with official verification, practical checklists and clear next steps.', 'The GOV.UK formation flow separates company-name rules from trademark checks and recommends confirming the proposed name is available.', ['Check the company-name rules.','Check existing company names.','Search relevant trademarks before committing to the brand.','Retain the checks for internal governance.']);
$phase2['uk/registered-office-and-sic']=p2_make($sources['uk'], 'uk/registered-office-and-sic', 'Registered Office and SIC Code in UK', 'Registered Office and SIC Code in UK', 'Source-backed INCORPSYS guide to registered office and SIC code in UK, with official verification, practical checklists and clear next steps.', 'UK registration requires an official registered office and a SIC code that identifies the company’s business activity.', ['Choose an address that satisfies the registered-office rules.','Select the appropriate SIC code.','Keep address and activity details current.','Separate incorporation details from any separate operating licence.']);
$phase2['uk/online-registration']=p2_make($sources['uk'], 'uk/online-registration', 'Online Company Registration in UK', 'Online Company Registration in UK', 'Source-backed INCORPSYS guide to online company registration in UK, with official verification, practical checklists and clear next steps.', 'GOV.UK provides an online registration route and may set up Corporation Tax at the same time unless the company is dormant.', ['Create the required Government Gateway access where needed.','Complete the company details accurately.','Provide PSC and officer information.','Save the incorporation confirmation and company number.']);
$phase2['uk/certificate-of-incorporation']=p2_make($sources['uk'], 'uk/certificate-of-incorporation', 'Certificate of Incorporation in UK', 'Certificate of Incorporation in UK', 'Source-backed INCORPSYS guide to certificate of incorporation in UK, with official verification, practical checklists and clear next steps.', 'The certificate of incorporation confirms that the company legally exists and records the company number and date of formation.', ['Store the certificate securely.','Use the company number consistently across records.','Set up the corporate records required after formation.','Do not treat incorporation as completion of all compliance duties.']);
$phase2['uk/post-registration']=p2_make($sources['uk'], 'uk/post-registration', 'Post-Registration Checklist in UK', 'Post-Registration Checklist in UK', 'Source-backed INCORPSYS guide to the post-registration checklist in UK, with official verification, practical checklists and clear next steps.', 'GOV.UK directs newly incorporated companies to follow-up steps such as adding Corporation Tax services and checking the next statutory actions.', ['Open the current post-registration guidance.','Set up the business tax account where applicable.','Calendar company filing and tax obligations.','Review registered-office and officer information when changes occur.']);

$phase2['usa/business-location']=p2_make($sources['usa'], 'usa/business-location', 'Choosing a Business Location in USA', 'Choosing a Business Location in USA', 'Source-backed INCORPSYS guide to choosing a business location in USA, with official verification, practical checklists and clear next steps.', 'The U.S. SBA explains that business location affects taxes, zoning, regulations, registration and licensing requirements.', ['Decide the target state and locality first.','Check the local registration environment.','Map state, county and city requirements.','Compare only like-for-like official requirements.']);
$phase2['usa/business-structure']=p2_make($sources['usa'], 'usa/business-structure', 'Choosing a Business Structure in USA', 'Choosing a Business Structure in USA', 'Source-backed INCORPSYS guide to choosing a business structure in USA, with official verification, practical checklists and clear next steps.', 'The SBA explains that business structure affects taxes, liability, fundraising and filing obligations and should be selected before registration.', ['Review the available structure choices for the target state.','Consider liability and tax consequences with qualified advisers.','Confirm the structure before preparing filings.','Check whether the structure affects licensing or reporting.']);
$phase2['usa/business-name']=p2_make($sources['usa'], 'usa/business-name', 'Choosing a Business Name in USA', 'Choosing a Business Name in USA', 'Source-backed INCORPSYS guide to choosing a business name in USA, with official verification, practical checklists and clear next steps.', 'SBA guidance includes business-name selection as a distinct startup step before registration.', ['Check the state name-availability rules.','Consider a DBA or trade-name requirement if applicable.','Search relevant trademarks separately.','Keep the final name consistent in filings.']);
$phase2['usa/state-registration']=p2_make($sources['usa'], 'usa/state-registration', 'State Business Registration in USA', 'State Business Registration in USA', 'Source-backed INCORPSYS guide to state business registration in USA, with official verification, practical checklists and clear next steps.', 'SBA guidance explains that registration depends on the business structure and location and often involves the state-level filing authority.', ['Identify the correct state filing agency.','Prepare the structure-specific formation document.','Check whether local registration is also required.','Retain the filed certificate or confirmation.']);
$phase2['usa/registered-agent']=p2_make($sources['usa'], 'usa/registered-agent', 'Registered Agent in USA', 'Registered Agent in USA', 'Source-backed INCORPSYS guide to registered agent in USA, with official verification, practical checklists and clear next steps.', 'For LLCs, corporations, partnerships and nonprofits, the SBA notes that a registered agent is needed in the state where the entity registers.', ['Confirm whether the entity needs a registered agent.','Choose an eligible in-state agent.','Keep the registered-agent address current.','Retain the appointment evidence.']);
$phase2['usa/foreign-qualification']=p2_make($sources['usa'], 'usa/foreign-qualification', 'Foreign Qualification in USA', 'Foreign Qualification in USA', 'Source-backed INCORPSYS guide to foreign qualification in USA, with official verification, practical checklists and clear next steps.', 'The SBA explains that an entity active in more than one state may need foreign qualification in additional states.', ['Identify where the business will actually operate.','Check the target state’s foreign-qualification rules.','Prepare the required foreign registration filing.','Calendar ongoing reports in each relevant state.']);
$phase2['usa/tax-ids']=p2_make($sources['usa'], 'usa/tax-ids', 'Federal and State Tax IDs in USA', 'Federal and State Tax IDs in USA', 'Source-backed INCORPSYS guide to federal and state tax IDs in USA, with official verification, practical checklists and clear next steps.', 'SBA startup guidance separates registration from obtaining federal and state tax identification numbers.', ['Determine which tax IDs the business needs.','Apply through the appropriate government channel.','Keep tax records separate from incorporation records.','Verify state-specific tax registrations.']);
$phase2['usa/licenses-and-permits']=p2_make($sources['usa'], 'usa/licenses-and-permits', 'Licences and Permits in USA', 'Licences and Permits in USA', 'Source-backed INCORPSYS guide to licences and permits in USA, with official verification, practical checklists and clear next steps.', 'The SBA explains that licenses and permits depend on business activity and location and can be required at state, county or city level.', ['Identify the regulated activities.','Check state requirements.','Check county and city requirements.','Track expiry and renewal dates where applicable.']);
$phase2['usa/local-agencies']=p2_make($sources['usa'], 'usa/local-agencies', 'Local Registration and Permits in USA', 'Local Registration and Permits in USA', 'Source-backed INCORPSYS guide to local registration and permits in USA, with official verification, practical checklists and clear next steps.', 'Local governments can impose their own registration, licensing and permitting requirements, so the SBA recommends checking the relevant local authority.', ['Identify the city and county agencies.','Check DBA or local business registration rules.','Map local permits to the operating address.','Keep local certificates and approvals accessible.']);
$phase2['usa/ongoing-state-reports']=p2_make($sources['usa'], 'usa/ongoing-state-reports', 'Ongoing State Reporting in USA', 'Ongoing State Reporting in USA', 'Source-backed INCORPSYS guide to ongoing state reporting in USA, with official verification, practical checklists and clear next steps.', 'The SBA notes that some states require additional reports soon after registration and that obligations vary by state and structure.', ['Check the state filing calendar.','Record initial reports or tax-board registration where applicable.','Confirm renewal and annual report rules.','Review the official state page after material business changes.']);

$phase2['malaysia/company-types']=p2_make($sources['malaysia'], 'malaysia/company-types', 'Company Types in Malaysia', 'Company Types in Malaysia', 'Source-backed INCORPSYS guide to company types in Malaysia, with official verification, practical checklists and clear next steps.', 'SSM lists company limited by shares, company limited by guarantee and unlimited company as company types under the Companies Act 2016.', ['Choose the company type based on the intended legal structure.','Confirm the route available to the proposed promoter(s).','Use the SSM source as the controlling reference.','Keep the chosen type consistent through the application.']);
$phase2['malaysia/basic-incorporation-requirements']=p2_make($sources['malaysia'], 'malaysia/basic-incorporation-requirements', 'Basic Incorporation Requirements in Malaysia', 'Basic Incorporation Requirements in Malaysia', 'Source-backed INCORPSYS guide to basic incorporation requirements in Malaysia, with official verification, practical checklists and clear next steps.', 'SSM sets out baseline requirements for private and public companies, including directors who ordinarily reside in Malaysia and promoter requirements.', ['Identify promoter(s) and director(s).','Check the residence requirements.','Confirm whether a private or public company route is appropriate.','Retain the source used for the eligibility review.']);
$phase2['malaysia/company-name-approval']=p2_make($sources['malaysia'], 'malaysia/company-name-approval', 'Company Name Approval in Malaysia', 'Company Name Approval in Malaysia', 'Source-backed INCORPSYS guide to company name approval in Malaysia, with official verification, practical checklists and clear next steps.', 'SSM’s incorporation process requires approval of the proposed company name before the incorporation application proceeds through the relevant route.', ['Prepare a proposed company name.','Submit the required name application.','Record the approval details.','Complete incorporation within the authority’s stated period.']);
$phase2['malaysia/direct-incorporation']=p2_make($sources['malaysia'], 'malaysia/direct-incorporation', 'Direct Incorporation in Malaysia', 'Direct Incorporation in Malaysia', 'Source-backed INCORPSYS guide to direct incorporation in Malaysia, with official verification, practical checklists and clear next steps.', 'SSM permits an online direct-incorporation method that combines name reservation and incorporation, alongside a separate name-reservation route.', ['Choose the direct route or reservation route.','Use the MyCoID process.','Complete the required incorporation particulars.','Retain payment and submission evidence.']);
$phase2['malaysia/name-reservation-window']=p2_make($sources['malaysia'], 'malaysia/name-reservation-window', 'Name Reservation Window in Malaysia', 'Name Reservation Window in Malaysia', 'Source-backed INCORPSYS guide to name reservation window in Malaysia, with official verification, practical checklists and clear next steps.', 'SSM states that after name approval, the incorporation application should be submitted within 30 days or a longer period allowed by the Registrar, up to the published maximum.', ['Record the name approval date.','Calendar the filing deadline.','Complete incorporation within the allowed period.','Recheck the live SSM guidance if timing changes.']);
$phase2['malaysia/incorporation-particulars']=p2_make($sources['malaysia'], 'malaysia/incorporation-particulars', 'Incorporation Particulars and Super Form in Malaysia', 'Incorporation Particulars and Super Form in Malaysia', 'Source-backed INCORPSYS guide to incorporation particulars and super form in Malaysia, with official verification, practical checklists and clear next steps.', 'SSM identifies core incorporation particulars covering company type, business activity, registered office, business address, directors, promoters and declarations.', ['Prepare the proposed company name.','Prepare business and registered-office details.','Prepare director and promoter particulars.','Complete declarations and any supporting documents.']);
$phase2['malaysia/director-requirements']=p2_make($sources['malaysia'], 'malaysia/director-requirements', 'Director Requirements in Malaysia', 'Director Requirements in Malaysia', 'Source-backed INCORPSYS guide to director requirements in Malaysia, with official verification, practical checklists and clear next steps.', 'SSM states that a director must be a natural person, at least 18, ordinarily resident in Malaysia and meet the other published eligibility conditions.', ['Confirm age and natural-person status.','Confirm principal or ordinary residence in Malaysia.','Check bankruptcy and disqualification conditions.','Keep identification and consent documents ready.']);
$phase2['malaysia/company-secretary']=p2_make($sources['malaysia'], 'malaysia/company-secretary', 'Company Secretary Appointment in Malaysia', 'Company Secretary Appointment in Malaysia', 'Source-backed INCORPSYS guide to company secretary appointment in Malaysia, with official verification, practical checklists and clear next steps.', 'SSM requires the first company secretary to be appointed within the stated period after incorporation and sets eligibility conditions for the secretary.', ['Identify an eligible licensed or professional secretary.','Calendar the appointment deadline.','Retain the appointment filing evidence.','Use the latest SSM rules for any exception.']);
$phase2['malaysia/registered-office-rules']=p2_make($sources['malaysia'], 'malaysia/registered-office-rules', 'Registered Office in Malaysia', 'Registered Office in Malaysia', 'Source-backed INCORPSYS guide to the registered office in Malaysia, with official verification, practical checklists and clear next steps.', 'SSM states that a company must maintain a registered office in Malaysia and describes the address details that should be provided.', ['Prepare a complete Malaysian registered office address.','Check unit, level, building, road, city, postcode and state details.','Keep the address updated.','Retain proof of address where required.']);
$phase2['malaysia/annual-submission']=p2_make($sources['malaysia'], 'malaysia/annual-submission', 'Annual Submission and Annual Return in Malaysia', 'Annual Submission and Annual Return in Malaysia', 'Source-backed INCORPSYS guide to annual submission and annual return in Malaysia, with official verification, practical checklists and clear next steps.', 'SSM states that registered companies must lodge annual submissions, including an annual return containing key company information.', ['Calendar the annual return deadline.','Keep director, secretary, member and registered-office details current.','Prepare the relevant annual submission information.','Retain filing evidence.']);

$phase2['resources/start-company-abroad']=p2_make($global, 'resources/start-company-abroad', 'Starting a Company Abroad', 'Starting a Company Abroad', 'A source-first framework for planning international company incorporation without assuming that one jurisdiction or structure fits every business.', 'Start with the target activity, ownership profile, operating location and the official authority for the destination. Then build the incorporation checklist from current source material.', ['Define the business activity and operating model.','Select a short list of jurisdictions without ranking them prematurely.','Confirm the official registration authority for each jurisdiction.','Separate incorporation from tax, licensing, banking and immigration decisions.']);
$phase2['resources/choose-jurisdiction-framework']=p2_make($global, 'resources/choose-jurisdiction-framework', 'How to Choose a Jurisdiction', 'How to Choose a Jurisdiction', 'A neutral framework for comparing incorporation jurisdictions using official requirements, operating realities and the founder’s actual business objective.', 'There is no universal “best” jurisdiction. A sound decision compares structure, activity, address, compliance, tax and operating requirements for the specific business.', ['Compare like-for-like entity types.','Verify activity-specific licences.','Check local office or address rules.','Model ongoing compliance as well as initial setup.']);
$phase2['resources/source-first-research']=p2_make($global, 'resources/source-first-research', 'Source-First Company Formation Research', 'Source-First Company Formation Research', 'A practical research method that prioritizes official registries and government authorities before provider articles or promotional material.', 'Use third-party pages to understand questions, but use the relevant government or registry page to verify the rule before filing, paying or promising a client outcome.', ['Find the responsible authority.','Read the current procedural guide.','Record source date and URL.','Cross-check critical requirements before execution.']);
$phase2['resources/company-name-checklist']=p2_make($global, 'resources/company-name-checklist', 'Company Name Verification Checklist', 'Company Name Verification Checklist', 'A structured checklist for reviewing a proposed company name before documents or marketing materials are finalized.', 'Name rules are jurisdiction-specific; the official registry should be used to verify availability, restricted terms and the final registrability route.', ['Check existing and reserved names.','Review restricted words and protected names.','Check trademark conflicts separately.','Keep the search evidence.']);
$phase2['resources/business-activity-mapping']=p2_make($global, 'resources/business-activity-mapping', 'Business Activity Mapping', 'Business Activity Mapping', 'A source-backed method for translating a business idea into the activity classification used by the relevant incorporation or licensing authority.', 'Business activity should be defined before choosing a legal form or licence whenever the authority’s process uses activity as a decision input.', ['Describe the activity in plain language.','Map it to the authority’s classification.','Identify regulated or referral activities.','Record the selected code or category.']);
$phase2['resources/legal-form-decision']=p2_make($global, 'resources/legal-form-decision', 'Legal Form Decision Framework', 'Legal Form Decision Framework', 'A neutral framework for choosing among available legal forms without treating one structure as universally superior.', 'Choose the structure only after reviewing ownership, liability, activity, governance and filing requirements in the target jurisdiction.', ['List the available legal forms.','Match each form to the business activity.','Review owner/director requirements.','Confirm the final form with the official authority.']);
$phase2['resources/registered-office-checklist']=p2_make($global, 'resources/registered-office-checklist', 'Registered Office Checklist', 'Registered Office Checklist', 'A cross-jurisdiction checklist for preparing the official address information required during incorporation.', 'Registered-office rules vary by jurisdiction; use the authority source to confirm address eligibility and documentary requirements.', ['Prepare the full legal address.','Confirm local-address requirements.','Check whether virtual or service addresses are permitted.','Record address-change procedures.']);
$phase2['resources/director-shareholder-prep']=p2_make($global, 'resources/director-shareholder-prep', 'Director and Shareholder Preparation', 'Director and Shareholder Preparation', 'A preparation guide for the people and ownership information that commonly appears in incorporation filings.', 'Before filing, identify the proposed directors, shareholders, promoters or members and verify the exact authority requirements for each role.', ['Collect full legal names and IDs.','Confirm role eligibility.','Prepare ownership information.','Check whether a local-resident role is required.']);
$phase2['resources/documents-master-checklist']=p2_make($global, 'resources/documents-master-checklist', 'Master Incorporation Documents Checklist', 'Master Incorporation Documents Checklist', 'A cross-jurisdiction document-control framework for preparing incorporation information without inventing a universal document list.', 'The exact list must come from the official authority and can vary by entity type, activity and applicant profile.', ['Identity documents.','Company-name and structure data.','Registered-office information.','Director/shareholder/promoter particulars.']);
$phase2['resources/authority-vs-provider']=p2_make($global, 'resources/authority-vs-provider', 'Authority Rules vs Service-Provider Workflow', 'Authority Rules vs Service-Provider Workflow', 'How to distinguish statutory requirements from the additional documents a professional service provider may request for its own workflow.', 'Government authorities define the legal filing requirements; providers can request extra documents for due diligence, KYC or service delivery.', ['Label each requirement as authority or provider.','Link each statutory requirement to its source.','Do not present provider checklists as law.','Keep the source version/date.']);
$phase2['resources/fee-verification']=p2_make($global, 'resources/fee-verification', 'How to Verify Government Fees', 'How to Verify Government Fees', 'A process for checking official fees before quoting, collecting or paying for an incorporation service.', 'Use the current authority fee table or application portal at the point of transaction rather than relying on stale third-party fee articles.', ['Open the current official fee page.','Check entity type and filing route.','Separate government charges from service fees.','Record the date checked.']);
$phase2['resources/timeline-verification']=p2_make($global, 'resources/timeline-verification', 'How to Verify Registration Timelines', 'How to Verify Registration Timelines', 'A source-first approach to published processing times and the difference between official service timing and third-party workflow estimates.', 'Timelines can vary with referral reviews, document quality and the selected filing route; use the authority’s current service information before communicating a timing expectation.', ['Check official processing information.','Identify referral or review dependencies.','Separate filing time from client preparation.','Avoid guaranteed approval dates.']);
$phase2['resources/licence-and-approval-mapping']=p2_make($global, 'resources/licence-and-approval-mapping', 'Licence and Approval Mapping', 'Licence and Approval Mapping', 'A structured way to identify whether an incorporation route also needs a sector licence, permit or approval.', 'Company registration does not automatically authorize every business activity; regulated activities may have separate authorities and approvals.', ['Identify the business activity.','Search the authority’s licensing guidance.','Map additional approvals.','Track approval evidence separately from incorporation evidence.']);
$phase2['resources/post-incorporation-calendar']=p2_make($global, 'resources/post-incorporation-calendar', 'Post-Incorporation Compliance Calendar', 'Post-Incorporation Compliance Calendar', 'A framework for converting a new company into a managed corporate calendar after incorporation.', 'After incorporation, identify recurring filings, licence renewals, registered-information changes and tax or corporate obligations from official guidance.', ['List recurring filings.','Calendar licence renewals.','Record tax registration or reporting dates where applicable.','Assign an owner to each deadline.']);
$phase2['resources/banking-readiness']=p2_make($global, 'resources/banking-readiness', 'Corporate Banking Readiness', 'Corporate Banking Readiness', 'A preparation guide for separating incorporation documents from the bank’s own account-opening requirements.', 'Banking requirements are institution-specific and should be confirmed directly with the chosen bank; company incorporation alone does not guarantee account approval.', ['Prepare corporate documents.','Identify authorized signatories.','Prepare business-purpose and ownership information.','Check the bank’s current onboarding list.']);
$phase2['resources/tax-authority-handoff']=p2_make($global, 'resources/tax-authority-handoff', 'Tax Authority Handoff', 'Tax Authority Handoff', 'How to keep incorporation, tax registration and ongoing tax compliance as separate but coordinated workstreams.', 'Tax registration requirements depend on the jurisdiction, entity and activity and should be verified with the relevant tax authority.', ['Identify the tax authority.','Check registration triggers.','Confirm filing deadlines.','Keep tax registrations linked to the corporate record.']);
$phase2['resources/visa-vs-incorporation']=p2_make($global, 'resources/visa-vs-incorporation', 'Visa and Residency vs Company Incorporation', 'Visa and Residency vs Company Incorporation', 'A clear distinction between forming a company and obtaining immigration or residency status.', 'Incorporation and immigration are separate legal processes. Each has its own authority, eligibility rules and approval criteria.', ['Complete the corporate-formation analysis.','Identify the immigration authority separately.','Check visa eligibility independently.','Do not promise a residency outcome based only on incorporation.']);
$phase2['resources/foreign-founder-preparation']=p2_make($global, 'resources/foreign-founder-preparation', 'Foreign Founder Preparation', 'Foreign Founder Preparation', 'A preparation guide for founders establishing a business outside their home country.', 'Foreign-founder requirements can include local-resident roles, identity verification, certified documents and immigration considerations, all of which are jurisdiction-specific.', ['Confirm founder eligibility.','Prepare identity documents in the required format.','Check local-resident rules.','Separate company formation from immigration.']);
$phase2['resources/cross-border-expansion']=p2_make($global, 'resources/cross-border-expansion', 'Cross-Border Expansion Planning', 'Cross-Border Expansion Planning', 'A structured way to plan a second-country or multi-country expansion after the first business is established.', 'Treat each market as a separate regulatory environment and verify local incorporation, tax, licensing and operating requirements.', ['Define the expansion purpose.','Map the target market activity.','Choose branch, subsidiary or another lawful route.','Build a local compliance calendar.']);
$phase2['resources/branch-vs-subsidiary']=p2_make($global, 'resources/branch-vs-subsidiary', 'Branch vs Subsidiary: Questions to Verify', 'Branch vs Subsidiary: Questions to Verify', 'A neutral comparison framework for deciding whether a market entry should use a branch or subsidiary where both are available.', 'The appropriate structure depends on the target jurisdiction’s rules, the parent company’s profile and the intended operating model.', ['Compare liability and governance.','Check local filing requirements.','Check tax and regulatory treatment.','Confirm the authority route before deciding.']);
$phase2['resources/local-agent-concepts']=p2_make($global, 'resources/local-agent-concepts', 'Local Agent and Representative Requirements', 'Understanding Local Agent or Representative Requirements', 'An explainer for jurisdictions where local-resident persons, agents or corporate-service providers may play a role in registration.', 'Do not assume that “local agent” has the same legal meaning in every country; verify the exact role, eligibility and statutory basis from the authority.', ['Identify the role in the law or official guidance.','Confirm eligibility.','Check appointment or contract requirements.','Avoid using generic terms as legal equivalents.']);
$phase2['resources/compliance-evidence']=p2_make($global, 'resources/compliance-evidence', 'Corporate Compliance Evidence File', 'Corporate Compliance Evidence File', 'How to maintain a defensible file of filings, approvals, certificates and source pages.', 'A source-backed corporate file should show what was filed, where it was filed, when it was accepted and which authority guidance controlled the step.', ['Save filing receipts.','Store certificates.','Keep source URLs and dates.','Record material changes and updates.']);
$phase2['resources/document-version-control']=p2_make($global, 'resources/document-version-control', 'Document Version Control for Incorporation', 'Document Version Control for Incorporation', 'A practical method for controlling changing corporate documents across a multi-step incorporation workflow.', 'Version control reduces accidental submission of superseded forms or documents and helps the team know which source was used for each decision.', ['Use a consistent filename convention.','Record preparation and approval dates.','Archive superseded versions.','Link final files to the filing transaction.']);
$phase2['resources/filing-proof']=p2_make($global, 'resources/filing-proof', 'How to Preserve Filing Proof', 'How to Preserve Filing Proof', 'A checklist for preserving electronic and hard-copy evidence of incorporation and related submissions.', 'Keep enough evidence to reconstruct the filing journey without relying on memory or a provider dashboard alone.', ['Save confirmation emails.','Download official certificates.','Store transaction numbers.','Record filing dates and authority names.']);
$phase2['resources/source-freshness']=p2_make($global, 'resources/source-freshness', 'Source Freshness and Regulatory Updates', 'Source Freshness and Regulatory Updates', 'A source-governance page explaining how INCORPSYS should keep regulatory content aligned with live official guidance.', 'Regulatory information is time-sensitive; page content should be reviewed against the linked authority before a user acts on a rule.', ['Record the last verification date.','Monitor official update pages.','Recheck fees and processing times.','Flag pages that require a fresh review.']);
$phase2['resources/how-to-read-official-guidance']=p2_make($global, 'resources/how-to-read-official-guidance', 'How to Read Official Incorporation Guidance', 'How to Read Official Incorporation Guidance', 'A reading method for government and registry pages so users can distinguish mandatory steps, optional routes and linked approvals.', 'Start with the issuing authority, identify the legal entity or activity scope, then follow the official process in the order presented.', ['Identify the authority.','Confirm the exact entity type.','Read exceptions and referral notes.','Save the specific service page used.']);
$phase2['resources/company-incorporation-faq']=p2_make($global, 'resources/company-incorporation-faq', 'Company Incorporation FAQ', 'Company Incorporation FAQ', 'Direct-answer questions designed to help users understand the source-backed company-incorporation workflow.', 'Company incorporation is the legal process of creating a company or other registered business entity under the rules of a specific jurisdiction; the exact steps depend on the authority and structure.', ['Who is the registering authority?','What entity type is being formed?','Which documents are mandatory?','What happens after incorporation?']);
$phase2['resources/jurisdiction-faq']=p2_make($global, 'resources/jurisdiction-faq', 'Choosing a Jurisdiction FAQ', 'Choosing a Jurisdiction FAQ', 'Direct-answer questions for early-stage users comparing international incorporation options without a ranking.', 'The right jurisdiction depends on the business activity, ownership, operating location, structure, compliance and tax considerations, all of which should be checked against official sources.', ['What is the business activity?','Where will the business operate?','What local roles are required?','What ongoing filings apply?']);
$phase2['resources/incorporation-glossary']=p2_make($global, 'resources/incorporation-glossary', 'Global Incorporation Glossary', 'Global Incorporation Glossary', 'A practical glossary of common company-formation terms used across different jurisdictions.', 'Terminology such as registered office, shareholder, director, promoter, PSC, company secretary and registered agent can have different legal meanings by country.', ['Use the local authority definition.','Do not assume terms are interchangeable.','Check entity-specific context.','Link each term to the relevant source.']);
$phase2['resources/registration-glossary']=p2_make($global, 'resources/registration-glossary', 'Company Registration Glossary', 'Company Registration Glossary', 'A plain-language glossary focused on filing, registry and incorporation terms.', 'Registration terminology should be read in the context of the authority that uses it.', ['Registry','Incorporation','Reservation','Filing','Certificate']);
$phase2['resources/compliance-glossary']=p2_make($global, 'resources/compliance-glossary', 'Corporate Compliance Glossary', 'Corporate Compliance Glossary', 'A practical glossary of recurring compliance and corporate-record terms.', 'Compliance terms vary by jurisdiction, so the local authority definition should control.', ['Annual return','Registered office','PSC','Company secretary','Statutory records']);
$phase2['resources/startup-global-setup-checklist']=p2_make($global, 'resources/startup-global-setup-checklist', 'Startup Global Setup Checklist', 'Startup Global Setup Checklist', 'A practical checklist for founders preparing an international company setup project.', 'A strong startup setup file starts with the operating plan and then maps legal structure, activity, ownership, registration and compliance requirements.', ['Business model defined.','Target market identified.','Structure reviewed.','Source-backed filing checklist prepared.']);
$phase2['resources/service-provider-due-diligence']=p2_make($global, 'resources/service-provider-due-diligence', 'Service Provider Due Diligence Checklist', 'Service Provider Due Diligence Checklist', 'Questions to ask before appointing a third-party incorporation or compliance provider.', 'A provider should be able to distinguish statutory requirements from its own service workflow and point to the underlying authority source.', ['Ask for the statutory source.','Separate government fees from service fees.','Confirm deliverables in writing.','Check data and document handling.']);
$phase2['resources/enquiry-preparation']=p2_make($global, 'resources/enquiry-preparation', 'Prepare an Incorporation Enquiry', 'Prepare an Incorporation Enquiry', 'A checklist for giving INCORPSYS enough information to structure a source-backed company-setup response.', 'A useful enquiry identifies the intended market, activity, founder profile, ownership structure and desired outcome without sending unnecessary sensitive data.', ['Target jurisdiction.','Business activity.','Founder/ownership profile.','Immediate objective.']);
$phase2['contact']=[
  'slug'=>'contact','jurisdiction'=>null,'kind'=>'contact','name'=>'Contact INCORPSYS','title'=>'Contact INCORPSYS | INCORPSYS','h1'=>'Contact INCORPSYS','eyebrow'=>'CONTACT',
  'description'=>'Contact INCORPSYS for global company incorporation and international business setup enquiries.','answer'=>'Use the INCORPSYS enquiry form, email, phone or WhatsApp route to discuss a company incorporation or international business setup requirement.',
  'sections'=>[
    ['title'=>'Page purpose','body'=>'Contact INCORPSYS for global company incorporation and international business setup enquiries.'],
    ['title'=>'Key information','bullets'=>['Email: hello@incorpsys.com','Phone / WhatsApp: +91 78448 19819','Online enquiry form on the website','Do not send passwords or sensitive financial information through the public enquiry form.']],
  ],
  'faqs'=>[
    ['q'=>'Where can I get the latest official or business information?','a'=>'For regulatory rules, use the relevant government or registry source. For INCORPSYS service enquiries, use the website contact options.'],
    ['q'=>'Can this page replace legal advice?','a'=>'No. It is informational website content and should not be treated as a substitute for professional advice.'],
    ['q'=>'How do I start an enquiry?','a'=>'Use the Enquiry Now button or contact hello@incorpsys.com or +91 78448 19819.'],
    ['q'=>'What is the INCORPSYS contact email?','a'=>'hello@incorpsys.com'],
  ],
  'source'=>null,'verified'=>'2026-09-25'
];
$phase2['resources/official-sources-directory']=p2_make($global, 'resources/official-sources-directory', 'INCORPSYS Official Source Directory', 'INCORPSYS Official Source Directory', 'A directory of the government and registry sources used as primary references for the INCORPSYS jurisdiction guides.', 'Use this directory to move from an INCORPSYS summary to the competent government or registry page for the exact jurisdiction, entity and activity.', ['UAE Government','ACRA Singapore','Companies Registry Hong Kong','GOV.UK / Companies House','U.S. Small Business Administration','SSM Malaysia']);
$phase2['legal/privacy']=[
  'slug'=>'legal/privacy','jurisdiction'=>null,'kind'=>'legal','name'=>'Privacy Policy','title'=>'Privacy Policy | INCORPSYS','h1'=>'Privacy Policy','eyebrow'=>'LEGAL',
  'description'=>'INCORPSYS privacy policy page for the public website.','answer'=>'This page describes the categories of information that may be collected through the website and the principles applied to its handling; final legal text should be reviewed and approved before production publication.',
  'sections'=>[
    ['title'=>'Page purpose','body'=>'INCORPSYS privacy policy page for the public website.'],
    ['title'=>'Key information','bullets'=>['Contact-form information may include name, email, phone and enquiry details.','Website technical logs may be processed for security and operations.','Sensitive financial data should not be submitted through public forms.','Requests about personal data can be directed to INCORPSYS.']],
  ],
  'faqs'=>[
    ['q'=>'Where can I get the latest official or business information?','a'=>'For regulatory rules, use the relevant government or registry source. For INCORPSYS service enquiries, use the website contact options.'],
    ['q'=>'Can this page replace legal advice?','a'=>'No. It is informational website content and should not be treated as a substitute for professional advice.'],
    ['q'=>'How do I start an enquiry?','a'=>'Use the Enquiry Now button or contact hello@incorpsys.com or +91 78448 19819.'],
  ],
  'source'=>null,'verified'=>'2026-09-25'
];
$phase2['legal/terms']=[
  'slug'=>'legal/terms','jurisdiction'=>null,'kind'=>'legal','name'=>'Terms of Use','title'=>'Terms of Use | INCORPSYS','h1'=>'Terms of Use','eyebrow'=>'LEGAL',
  'description'=>'INCORPSYS terms of use page for the public website.','answer'=>'The website provides information and enquiry pathways; users should verify current legal and regulatory requirements with the competent authority before acting.',
  'sections'=>[
    ['title'=>'Page purpose','body'=>'INCORPSYS terms of use page for the public website.'],
    ['title'=>'Key information','bullets'=>['Official sources remain controlling.','Third-party services have their own terms.','No outcome is guaranteed by informational content.','Final legal text should be reviewed before publication.']],
  ],
  'faqs'=>[
    ['q'=>'Where can I get the latest official or business information?','a'=>'For regulatory rules, use the relevant government or registry source. For INCORPSYS service enquiries, use the website contact options.'],
    ['q'=>'Can this page replace legal advice?','a'=>'No. It is informational website content and should not be treated as a substitute for professional advice.'],
    ['q'=>'How do I start an enquiry?','a'=>'Use the Enquiry Now button or contact hello@incorpsys.com or +91 78448 19819.'],
  ],
  'source'=>null,'verified'=>'2026-09-25'
];
$phase2['legal/disclaimer']=[
  'slug'=>'legal/disclaimer','jurisdiction'=>null,'kind'=>'legal','name'=>'Website Disclaimer','title'=>'Website Disclaimer | INCORPSYS','h1'=>'Website Disclaimer','eyebrow'=>'LEGAL',
  'description'=>'INCORPSYS website disclaimer page for the public website.','answer'=>'INCORPSYS aims to use official sources and clear verification prompts, but government pages, fees, processes and eligibility can change; users should verify current information before filing, payment or operation.',
  'sections'=>[
    ['title'=>'Page purpose','body'=>'INCORPSYS website disclaimer page for the public website.'],
    ['title'=>'Key information','bullets'=>['Government and registry rules control.','Processing times can change.','Fees can change.','Regulated matters should be confirmed with the competent professional or authority.']],
  ],
  'faqs'=>[
    ['q'=>'Where can I get the latest official or business information?','a'=>'For regulatory rules, use the relevant government or registry source. For INCORPSYS service enquiries, use the website contact options.'],
    ['q'=>'Can this page replace legal advice?','a'=>'No. It is informational website content and should not be treated as a substitute for professional advice.'],
    ['q'=>'How do I start an enquiry?','a'=>'Use the Enquiry Now button or contact hello@incorpsys.com or +91 78448 19819.'],
  ],
  'source'=>null,'verified'=>'2026-09-25'
];

return $phase2;
