<?php
declare(strict_types=1);
return [
  'uae'=>['label'=>'UAE','authority'=>'UAE Government','url'=>'https://u.ae/en/information-and-services/business/doing-business-on-the-mainland/steps-to-start-a-business-on-the-mainland','title'=>'Steps to start a business on the mainland','note'=>'Official UAE Government guidance describes business activity selection, legal form, trade licensing, trade-name registration, initial approval, location and additional approvals.'],
  'singapore'=>['label'=>'Singapore','authority'=>'Accounting and Corporate Regulatory Authority (ACRA)','url'=>'https://www.acra.gov.sg/register/business/','title'=>'Registering a business','note'=>'ACRA provides official guidance covering eligibility, business structure, name reservation, registration through Bizfile and post-registration requirements.'],
  'hong-kong'=>['label'=>'Hong Kong','authority'=>'Companies Registry','url'=>'https://www.cr.gov.hk/en/services/register-company.htm','title'=>'Registration of a new company','note'=>'The Companies Registry explains local company types, name selection and core incorporation forms and documents.'],
  'uk'=>['label'=>'UK','authority'=>'GOV.UK / Companies House','url'=>'https://www.gov.uk/limited-company-formation/register-your-company','title'=>'Set up a private limited company: Register your company','note'=>'GOV.UK provides current guidance on online registration, company details, PSC information, registered office details and the certificate of incorporation.'],
  'usa'=>['label'=>'USA','authority'=>'U.S. Small Business Administration (SBA)','url'=>'https://www.sba.gov/counseling/launch-your-business/','title'=>'Launch your business','note'=>'The SBA explains that business location and structure determine registration, tax, licensing and permitting requirements, with state and local variations.'],
  'malaysia'=>['label'=>'Malaysia','authority'=>'Companies Commission of Malaysia (SSM)','url'=>'https://www.ssm.com.my/Pages/Register_Business_Company_LLP/Company/Starting_Company.aspx','title'=>'Incorporation of Company under the Companies Act 2016','note'=>'SSM publishes official company incorporation requirements and process information, including company types, name approval and director requirements.'],
];
