<?php require_once __DIR__.'/../includes/config.php';$pages=site_data();$reg=site_registry();$jKey=trim((string)($GLOBALS['PAGE_SLUG']??''),'/');$src=$reg['sources'][$jKey]??null;if(!$src){require __DIR__.'/../404.php';return;}
$jLabel=$src['label'];$list=array_filter($pages,fn($p)=>$p['jurisdiction']===$jKey);
$page=['slug'=>$jKey,'title'=>$jLabel.' Company Incorporation & Business Setup | INCORPSYS','description'=>'INCORPSYS guides and services for company incorporation and business setup in '.$jLabel.', each linked to '.$src['authority'].' for verification.'];
include __DIR__.'/../partials/header.php';?>
<main id="main"><section class="page-hero"><div class="container"><nav class="breadcrumbs" aria-label="Breadcrumb"><a href="/">Home</a> <span>›</span> <span aria-current="page"><?=e($jLabel)?></span></nav><div class="eyebrow">JURISDICTION</div><h1>Company incorporation in <?=e($jLabel)?></h1><p class="page-sub"><?=e($page['description'])?></p></div></section>
<section class="section" style="padding-top:26px"><div class="container"><div class="content-grid"><div><?php foreach(['topic'=>'Guides','service'=>'Services'] as $kind=>$heading): $items=array_filter($list,fn($p)=>$p['kind']===$kind); if(!$items) continue;?><h2 class="hub-h2"><?=e($heading)?></h2><div class="grid2"><?php foreach($items as $p):?><a class="card hub-card" href="<?=e(path_url($p['slug']))?>"><h3><?=e($p['name'])?></h3><p><?=e($p['description'])?></p></a><?php endforeach;?></div><?php endforeach;?></div><aside class="source"><div class="tag">OFFICIAL SOURCE</div><h3><?=e($src['authority'])?></h3><p><strong><?=e($src['title'])?></strong></p><p><?=e($src['note'])?></p><a href="<?=e($src['url'])?>" target="_blank" rel="noopener noreferrer">Open official source ↗</a><small>Source pages can change. Re-check before filing, payment or relying on a rule.</small></aside></div></div></section>
<section class="section" style="padding-top:0"><div class="container enquiry" id="enquiry"><div><div class="eyebrow" style="color:#8fc1ff">GET STARTED</div><h2>Planning a company in <?=e($jLabel)?>?</h2><p>Tell us your structure and business objective and we will organize the next step around the official source.</p></div><?php $formJurisdiction=$jLabel;include __DIR__.'/../partials/enquiry-form.php';?></div></section></main>
<script type="application/ld+json"><?=json_encode(['@context'=>'https://schema.org','@type'=>'CollectionPage','name'=>$page['title'],'description'=>$page['description'],'url'=>page_url($jKey),'breadcrumb'=>['@type'=>'BreadcrumbList','itemListElement'=>[['@type'=>'ListItem','position'=>1,'name'=>'Home','item'=>page_url('')],['@type'=>'ListItem','position'=>2,'name'=>$jLabel,'item'=>page_url($jKey)]]]],JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE)?></script>
<?php include __DIR__.'/../partials/footer.php';?>
