<?php require_once __DIR__.'/../includes/config.php';$pages=site_data();$reg=site_registry();$slug=trim((string)($GLOBALS['PAGE_SLUG']??''),'/');$page=$pages[$slug]??null;if(!$page){require __DIR__.'/../404.php';return;}
$jKey=$page['jurisdiction'];$src=$reg['sources'][$jKey];$jLabel=$src['label'];
$siblings=array_filter($pages,fn($p)=>$p['jurisdiction']===$jKey&&$p['slug']!==$slug);
$sameName=array_filter($pages,fn($p)=>$p['jurisdiction']!==$jKey&&$p['slug']===$p['jurisdiction'].'/'.substr($slug,strlen($jKey)+1));
include __DIR__.'/../partials/header.php';?>
<main id="main"><section class="page-hero"><div class="container"><nav class="breadcrumbs" aria-label="Breadcrumb"><a href="/">Home</a> <span>›</span> <a href="<?=e(path_url($jKey))?>"><?=e($jLabel)?></a> <span>›</span> <span aria-current="page"><?=e($page['name'])?></span></nav><div class="eyebrow"><?=e($page['eyebrow']??'INCORPSYS')?></div><h1><?=e($page['h1']??$page['title'])?></h1><p class="page-sub"><?=e($page['description']??'')?></p></div></section>
<section class="section" style="padding-top:26px"><div class="container"><div class="answer"><div class="answer-label">DIRECT ANSWER</div><div><?=e($page['answer']??'Use the official source linked on this page to verify current requirements.')?></div></div><div class="content-grid"><article class="article"><?php foreach(($page['sections']??[]) as $section): ?><section><h2><?=e($section['title'])?></h2><?php if(!empty($section['body'])):?><p><?=e($section['body'])?></p><?php endif;?><?php if(!empty($section['bullets'])):?><ul><?php foreach($section['bullets'] as $b):?><li><?=e($b)?></li><?php endforeach;?></ul><?php endif;?></section><?php endforeach;?><?php if(!empty($page['faqs'])):?><section><h2>Frequently asked questions</h2><?php foreach($page['faqs'] as $faq):?><div class="faq"><div class="q"><?=e($faq['q'])?></div><div><?=e($faq['a'])?></div></div><?php endforeach;?></section><?php endif;?><section><h2>Start an enquiry</h2><p>Call <a href="<?=e(tel_url())?>"><?=e(SITE_PHONE)?></a>, email <a href="mailto:<?=e(SITE_EMAIL)?>"><?=e(SITE_EMAIL)?></a>, or <a href="<?=e(wa_url())?>" target="_blank" rel="noopener">start a WhatsApp conversation</a>.</p></section></article><aside class="source"><?php if(!empty($page['source'])):?><div class="tag">OFFICIAL SOURCE</div><h3><?=e($page['source']['authority'])?></h3><p><strong><?=e($page['source']['title'])?></strong></p><p><?=e($page['source']['note'])?></p><a href="<?=e($page['source']['url'])?>" target="_blank" rel="noopener noreferrer">Open official source ↗</a><small>Source pages can change. Re-check before filing, payment or relying on a rule.</small><?php endif;?></aside></div></div></section>
<section class="section related" style="padding-top:0"><div class="container"><div class="related-grid"><div class="card"><h2>More for <?=e($jLabel)?></h2><?php foreach(['topic'=>'Guides','service'=>'Services'] as $kind=>$heading): $list=array_filter($siblings,fn($p)=>$p['kind']===$kind); if(!$list) continue;?><h3><?=e($heading)?></h3><ul class="link-list"><?php foreach($list as $p):?><li><a href="<?=e(path_url($p['slug']))?>"><?=e($p['name'])?></a></li><?php endforeach;?></ul><?php endforeach;?></div><?php if($sameName):?><div class="card"><h2><?=e($page['name'])?> in other jurisdictions</h2><ul class="link-list"><?php foreach($sameName as $p):?><li><a href="<?=e(path_url($p['slug']))?>"><?=e($reg['sources'][$p['jurisdiction']]['label'])?></a></li><?php endforeach;?></ul></div><?php endif;?></div></div></section>
<section class="section" style="padding-top:0"><div class="container enquiry" id="enquiry"><div><div class="eyebrow" style="color:#8fc1ff">READY TO MOVE FORWARD?</div><h2>Turn verified information into an action plan.</h2><p>Tell us the jurisdiction, structure and business objective so the next step can be organized around the applicable source.</p></div><?php $formJurisdiction=$jLabel;include __DIR__.'/../partials/enquiry-form.php';?></div></section></main>
<script type="application/ld+json"><?=json_encode(['@context'=>'https://schema.org','@type'=>'WebPage','name'=>$page['title'],'description'=>$page['description'],'url'=>page_url($page['slug']),'publisher'=>['@type'=>'Organization','name'=>'INCORPSYS','url'=>SITE_URL],'breadcrumb'=>['@type'=>'BreadcrumbList','itemListElement'=>[['@type'=>'ListItem','position'=>1,'name'=>'Home','item'=>page_url('')],['@type'=>'ListItem','position'=>2,'name'=>$jLabel,'item'=>page_url($jKey)],['@type'=>'ListItem','position'=>3,'name'=>$page['name'],'item'=>page_url($page['slug'])]]]],JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE)?></script>
<?php if(!empty($page['faqs'])):?><script type="application/ld+json"><?=json_encode(['@context'=>'https://schema.org','@type'=>'FAQPage','mainEntity'=>array_map(fn($x)=>['@type'=>'Question','name'=>$x['q'],'acceptedAnswer'=>['@type'=>'Answer','text'=>$x['a']]],$page['faqs'])],JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE)?></script><?php endif;?>
<?php include __DIR__.'/../partials/footer.php';?>
